

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: depth1004!

  thymeleaf:
    cache: false

  mvc:
    view:
      prefix: /WEB-INF/board/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          #show_sql: true
          format_sql: true

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate : INFO
      springframework:
        security : DEBUG
