

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: 1234

  thymeleaf:
    cache: false

  security:
    user:
      name: user
      password: 1234

  #  main:
#    web-application-type: none

  mvc:
    view:
      prefix: /WEB-INF/board/
      suffix: .jsp

  jpa:
    hibernate:
      properties:
        hibernate:
          #show_sql: true
          format_sql: true
      ddl-auto: create-drop


  h2:
    console:
      enabled: true

#logging:
#  level:
#    org:
#      hibernate :
#        type : trace
#      springframework:
#        security : DEBUG
